[build]
target="thumbv7em-none-eabihf"
# this is to ensure caching of the build artifacts
rust-wrapper = "$HOME/.cargo/bin/sccache"

rustflags=[
    "-C", "link-arg=-Tlink.x",
    "-Z", "threads=9",
    ]

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "gdb-multiarch -q -x openocd.gdb"
